### ISSUE TITLE
Help emulate device hardware

### ISSUE THREAD

**Issue by sabas1080** [anzellai/wandkit#1]
Hi @anzellai

Excellent project 

I'm trying to emulate and create a DIY version of the Kano wand with an ESP32 with these values

```
const (
	// Wand device name: Kano-Wand-XX-XX-XX
	Wand = "Kano-Wand"
)
```
and services
```
// INFO
const (
	// BleUUIDInformationService ...
	BleUUIDInformationService = "64a70010f6914b93a6f40968f5b648f8"
	// BleUUIDInformationOrganisationChar ...
	BleUUIDInformationOrganisationChar = "64a7000bf6914b93a6f40968f5b648f8"
	// BleUUIDInformationSwChar ...
	BleUUIDInformationSwChar = "64a70013f6914b93a6f40968f5b648f8"
	// BleUUIDInformationHwChar ...
	BleUUIDInformationHwChar = "64a70001f6914b93a6f40968f5b648f8"
)

// IO
const (
	// BleUUIDIOService ...
	BleUUIDIOService = "64a70012f6914b93a6f40968f5b648f8"
	// BleUUIDIOBatteryChar ...
	BleUUIDIOBatteryChar = "64a70007f6914b93a6f40968f5b648f8"
	// BleUUIDIOUserButtonChar ...
	BleUUIDIOUserButtonChar = "64a7000df6914b93a6f40968f5b648f8"
	// BleUUIDIOVibratorChar ...
	BleUUIDIOVibratorChar = "64a70008f6914b93a6f40968f5b648f8"
	// BleUUIDIOLedChar ...
	BleUUIDIOLedChar = "64a70009f6914b93a6f40968f5b648f8"
	// BleUUIDIOKeepAliveChar ...
	BleUUIDIOKeepAliveChar = "64a7000ff6914b93a6f40968f5b648f8"
)

// SENSOR
const (
	// BleUUIDSensorService ...
	BleUUIDSensorService = "64a70011f6914b93a6f40968f5b648f8"
	// BleUUIDSensorQuaternionsChar ...
	BleUUIDSensorQuaternionsChar = "64a70002f6914b93a6f40968f5b648f8"
	// BleUUIDSensorRawChar ...
	BleUUIDSensorRawChar = "64a7000af6914b93a6f40968f5b648f8"
	// BleUUIDSensorMotionChar ...
	BleUUIDSensorMotionChar = "64a7000cf6914b93a6f40968f5b648f8"
	// BleUUIDSensorMagnCalibrateChar ...
	BleUUIDSensorMagnCalibrateChar = "64a70021f6914b93a6f40968f5b648f8"
	// BleUUIDSensorQuaternionsResetChar ...
	BleUUIDSensorQuaternionsResetChar = "64a70004f6914b93a6f40968f5b648f8"
	// BleUUIDSensorTempChar ...
	BleUUIDSensorTempChar = "64a70014f6914b93a6f40968f5b648f8"
)
```
Your binary detects it, but the app on Android and Mac does not

My device name is "Kano-Wand-34-78-89"

Do you have any idea why this happens?

Thanks

**Comment by anzellai** [comment]
@sabas1080 - thanks for your interests! 
Do you have any logs/further information on how you run, and what it shows when you try to detect the Wand?

The underlying methods to scan the device are using GATT protocol, the "Kano-Wand-XXX" is only the manufacturer device "name", they all have different unique ID.
That's why my method is to scan all nearby BT devices, and when the device name matching the "Kano-Wand" prefix, I will connect to it.

Also, my library is far from complete and I have started another library exploring with gRPC protocol for easier client generation at https://github.com/anzellai/bluewand -- if you're into protobuf that kind of thing -- again, far from complete, but will be working on both libraries and hopefully anyone with a Wand can enjoy this can create amazing stuff around it.

**Comment by sabas1080** [comment]
@anzellai now I have an example of my device

https://github.com/sabas1080/KanoWandHack/blob/master/kano-hack/kano-hack.ino

**Comment by anzellai** [comment]
@sabas1080, that’s fantastic!

Since there are a few libraries/attempts to abstract the running of a Kano Coding Wand, I actually think it might be better for us to use a schema protocol, and collaborate on the same foot?

This case, we can all hack and come around for share knowledge.

Protobuf/gRPC seems portable and low level enough for our Go/C implementation, as you only need a client, and gRPC is perfect for Go server running everywhere.

Is Arduino your only use case?
Also I’d suggest your “hard coded” device name/ID to be freely configured through flag/config file... since some devices have funny behaviours registering the same BLE device, and you might want to emulate as a second/different device.

Great work nonetheless!

**Comment by sabas1080** [comment]
Can you make the application detect the device, but it is about updating the device, could we provide the default values of the characteriscs?

- Organisation
- Hardware build
- Software version

Please thanks

**Comment by anzellai** [comment]
Hi @sabas1080 -- sorry for my late response I have been very busy at work!

What's the use case for those metadata? Do you want to run some logic for different versions etc. to have different behaviours?

I can certainly create another endpoint to send the metadata, but it won't be anytime soon -- probably after Xmas though.
